basePath: /
definitions:
  models.Brand:
    properties:
      id:
        type: integer
      logo:
        type: integer
      name:
        type: string
      owner:
        type: string
      year:
        type: integer
    type: object
  models.Item:
    properties:
      brand_id:
        type: integer
      category:
        type: string
      id:
        type: integer
      image_id:
        type: integer
      is_available:
        type: boolean
      price:
        type: integer
      sex:
        type: string
      size:
        type: string
    type: object
  models.ItemsPatchPrice:
    properties:
      price:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: WEB лабы. Как я хочу спать.....
  title: "Clothes store \U0001F45A"
  version: "1.337"
paths:
  /brands:
    put:
      consumes:
      - application/json
      parameters:
      - description: new brand
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Brand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Add new brand
      tags:
      - brands
  /brands/{BRAND_ID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID of deleted brand
        in: path
        name: BRAND_ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete brand
      tags:
      - brands
    get:
      consumes:
      - application/json
      parameters:
      - description: ID of brand
        in: path
        name: BRAND_ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Brand'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get an information about one brand
      tags:
      - brands
    post:
      consumes:
      - application/json
      parameters:
      - description: ID of update brand
        in: path
        name: BRAND_ID
        required: true
        type: integer
      - description: updated brand
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Brand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update brand
      tags:
      - brands
  /items:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page size
        in: query
        name: page_size
        required: true
        type: integer
      - description: Number of page
        in: query
        name: page_num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Item'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all items
      tags:
      - items
    put:
      consumes:
      - application/json
      parameters:
      - description: new item
        in: body
        name: item_model
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Add new item
      tags:
      - items
  /items/{ITEM_ID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID of updated brand
        in: path
        name: ITEM_ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete item
      tags:
      - items
    get:
      consumes:
      - application/json
      parameters:
      - description: ITEM_ID
        in: path
        name: ITEM_ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get an information about item
      tags:
      - items
    patch:
      consumes:
      - application/json
      parameters:
      - description: Id of the item
        in: path
        name: ITEM_ID
        required: true
        type: integer
      - description: updated item
        in: body
        name: item_price
        required: true
        schema:
          $ref: '#/definitions/models.ItemsPatchPrice'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update items price
      tags:
      - items
    post:
      consumes:
      - application/json
      parameters:
      - description: ID of updated brand
        in: path
        name: ITEM_ID
        required: true
        type: integer
      - description: updated item
        in: body
        name: item_model
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update item
      tags:
      - items
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
