basePath: /
host: localhost:8080
info:
  contact: {}
  description: WEB лабы. Как я хочу спать.....
  title: "Clothes store \U0001F45A"
  version: "1.337"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- name: authentication
- name: items
- name: brands
- name: basket
